from PyQt5.QtWidgets import QVBoxLayout, QHBoxLayout, QLabel, QSlider, QSizePolicy, QButtonGroup, QPushButton
from gui.widgets.basicWidgets import CollapsibleBox, QRangeSlider, Label, LineEdit, ComboBox

class Sim_Ui(object):

    def setupUi(self, obj):
        """
        used to setup the layout and initialize graphs
        """

        obj.layout = QVBoxLayout()
        obj.setLayout(obj.layout)

#        obj.box_jet = CollapsibleBox("Jet and Motor Controls")
#        obj.layout.addWidget(obj.box_jet)
        obj.lbl_jet = Label("Jet and Motor Controls")
        obj.lbl_jet.setTitleStylesheet()

        obj.lbl_percent_drop = QLabel("Dropped Shots (%)")
        obj.box_percent_drop = LineEdit("10")
        obj.box_percent_drop.valRange(0, 100)
        obj.lbl_int = QLabel("Beam Intensity")
        obj.box_int = LineEdit("10")
        obj.box_int.valRange(0, 100)
        obj.lbl_motor_pos = QLabel("Motor Position (mm)")
        obj.box_motor_pos = LineEdit("0")
        obj.box_motor_pos.valRange(-1, 1)
        obj.lbl_jet_radius = QLabel("Jet Radius (mm)")
        obj.box_jet_radius = LineEdit("0.025")
        obj.box_jet_radius.valRange(0, 0.1)
        obj.lbl_jet_center = QLabel("Jet Center (mm)")
        obj.box_jet_center = LineEdit("0.03")
        obj.box_jet_center.valRange(-1, 1)
        obj.lbl_max_int = QLabel("Diffraction Intensity")
        obj.box_max_int = LineEdit("10")
        obj.box_max_int.valRange(0, 100)
        obj.lbl_bg = QLabel("Background Noise")
        obj.box_bg = LineEdit("0.05")
        obj.box_bg.valRange(0, 1)

#        obj.box_search = CollapsibleBox("Search Controls")
#        obj.layout.addWidget(obj.box_search)
        obj.lbl_search = Label("Search Controls")
        obj.lbl_search.setTitleStylesheet()

        obj.lbl_ave_time = QLabel("Averaging Time (s)")
        obj.box_ave_time = LineEdit("1")
        obj.box_ave_time.valRange(0.01, 100)
        obj.lbl_left = QLabel("Left Bound (mm)")
        obj.box_left = LineEdit("-0.1")
        obj.box_left.valRange(-100, 100)
        obj.lbl_right = QLabel("Right Bound (mm)")
        obj.box_right = LineEdit("0.1")
        obj.box_right.valRange(-100, 100)
        obj.lbl_step = QLabel("Motor Step (mm)")
        obj.box_step = LineEdit("0.005")
        obj.box_step.valRange(0.001, 1)
        obj.lbl_sim_tol = QLabel("Convergence Tolerance (mm)")
        obj.box_sim_tol = LineEdit("0.001")
        obj.box_sim_tol.valRange(0.0001, 1)
        obj.lbl_thresh = QLabel("Tracking Threshold (% max)")
        obj.box_thresh = LineEdit("90")
        obj.box_thresh.valRange(1, 99)
        obj.lbl_wait = QLabel("Wait Time (s)")
        obj.box_wait = LineEdit("5")
        obj.box_wait.valRange(0.01, 100)
        obj.cbox_sim_algorithm = ComboBox()
        obj.cbox_sim_algorithm.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Preferred)
        obj.cbox_sim_algorithm.addItem("Linear Scan")
        obj.cbox_sim_algorithm.addItem("Ternary Search")
        obj.bttn_start_tracking = QPushButton("Start Tracking")
        obj.bttn_start_tracking.setStyleSheet("\
            background-color: green;\
            font-size:16px;\
            ")
        obj.bttn_stop_tracking = QPushButton("Stop Tracking")
        obj.bttn_stop_tracking.setStyleSheet("\
            background-color: red;\
            font-size:16px;\
            ")
        obj.bttn_search = QPushButton("Search")
        obj.bttn_search.setStyleSheet("\
            background-color: yellow;\
            font-size:16px;\
            ")

        obj.layout_percent_drop = QHBoxLayout()
        obj.layout_percent_drop.addWidget(obj.lbl_percent_drop, 75)
        obj.layout_percent_drop.addWidget(obj.box_percent_drop)
        obj.layout_int = QHBoxLayout()
        obj.layout_int.addWidget(obj.lbl_int, 75)
        obj.layout_int.addWidget(obj.box_int)
        obj.layout_motor_pos = QHBoxLayout()
        obj.layout_motor_pos.addWidget(obj.lbl_motor_pos, 75)
        obj.layout_motor_pos.addWidget(obj.box_motor_pos)
        obj.layout_jet_radius = QHBoxLayout()
        obj.layout_jet_radius.addWidget(obj.lbl_jet_radius, 75)
        obj.layout_jet_radius.addWidget(obj.box_jet_radius)
        obj.layout_jet_center = QHBoxLayout()
        obj.layout_jet_center.addWidget(obj.lbl_jet_center, 75)
        obj.layout_jet_center.addWidget(obj.box_jet_center)
        obj.layout_max_int = QHBoxLayout()
        obj.layout_max_int.addWidget(obj.lbl_max_int, 75)
        obj.layout_max_int.addWidget(obj.box_max_int)
        obj.layout_bg = QHBoxLayout()
        obj.layout_bg.addWidget(obj.lbl_bg, 75)
        obj.layout_bg.addWidget(obj.box_bg)


#        obj.box_jet.setContentLayout(obj.layout)

        obj.layout_ave_time = QHBoxLayout()
        obj.layout_ave_time.addWidget(obj.lbl_ave_time, 75)
        obj.layout_ave_time.addWidget(obj.box_ave_time)
        obj.layout_left = QHBoxLayout()
        obj.layout_left.addWidget(obj.lbl_left, 75)
        obj.layout_left.addWidget(obj.box_left)
        obj.layout_right = QHBoxLayout()
        obj.layout_right.addWidget(obj.lbl_right, 75)
        obj.layout_right.addWidget(obj.box_right)
        obj.layout_step = QHBoxLayout()
        obj.layout_step.addWidget(obj.lbl_step, 75)
        obj.layout_step.addWidget(obj.box_step)
        obj.layout_sim_tol = QHBoxLayout()
        obj.layout_sim_tol.addWidget(obj.lbl_sim_tol, 75)
        obj.layout_sim_tol.addWidget(obj.box_sim_tol)
        obj.layout_thresh = QHBoxLayout()
        obj.layout_thresh.addWidget(obj.lbl_thresh, 75)
        obj.layout_thresh.addWidget(obj.box_thresh)
        obj.layout_wait = QHBoxLayout()
        obj.layout_wait.addWidget(obj.lbl_wait, 75)
        obj.layout_wait.addWidget(obj.box_wait)

        obj.layout_algorithm = QHBoxLayout()
        obj.layout_algorithm.addWidget(obj.cbox_sim_algorithm)
        obj.layout_start = QHBoxLayout()
        obj.layout_start.addWidget(obj.bttn_start_tracking)
        obj.layout_stop = QHBoxLayout()
        obj.layout_stop.addWidget(obj.bttn_stop_tracking)
        obj.layout_search = QHBoxLayout()
        obj.layout_search.addWidget(obj.bttn_search)

        obj.layout.addWidget(obj.lbl_jet)
        obj.layout.addLayout(obj.layout_percent_drop)
        obj.layout.addLayout(obj.layout_int)
        obj.layout.addLayout(obj.layout_motor_pos)
        obj.layout.addLayout(obj.layout_jet_radius)
        obj.layout.addLayout(obj.layout_jet_center)
        obj.layout.addLayout(obj.layout_max_int)
        obj.layout.addLayout(obj.layout_bg)
        obj.layout.addWidget(obj.lbl_search)
        obj.layout.addLayout(obj.layout_ave_time)
        obj.layout.addLayout(obj.layout_left)
        obj.layout.addLayout(obj.layout_right)
        obj.layout.addLayout(obj.layout_step)
        obj.layout.addLayout(obj.layout_sim_tol)
        obj.layout.addLayout(obj.layout_thresh)
        obj.layout.addLayout(obj.layout_wait)
        obj.layout.addLayout(obj.layout_algorithm)
        obj.layout.addLayout(obj.layout_start)
        obj.layout.addLayout(obj.layout_stop)
        obj.layout.addLayout(obj.layout_search)
